remote_theme: just-the-docs/just-the-docs

title: Meaningful Life
description: This is my life !
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://a0m0a.github.io" # the base hostname & protocol for your site, e.g. http://example.com
